# Generated by Django 5.2.13 on 2026-06-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0002_alter_sensorreading_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='auto_aeration_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pond',
            name='auto_aeration_threshold',
            field=models.FloatField(default=4.0),
        ),
        migrations.CreateModel(
            name='WaterWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('on', 'Running'), ('off', 'Stopped'), ('error', 'Error')], default='off', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_wheels', to='ponds.pond')),
            ],
        ),
    ]
