# Generated by Django 5.2.13 on 2026-06-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponds', '0003_pond_auto_aeration_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature (°C)'), ('ph', 'pH Level'), ('dissolved_oxygen', 'Dissolved Oxygen (mg/L)'), ('water_level', 'Water Level (m)'), ('light', 'Ambient Light (Lux)'), ('rain', 'Rain Level (mm)')], max_length=20),
        ),
    ]
